# Generated by Django 5.2.1 on 2025-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "total_debt",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "debt_status",
                    models.CharField(
                        choices=[("no_debt", "Нет долга"), ("has_debt", "Есть долг")],
                        default="no_debt",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
