# Generated by Django 5.2.1 on 2025-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_created_at_client_updated_at"),
        ("dealers", "0006_dealergroup_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="dealer_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="dealers.dealergroup",
            ),
            preserve_default=False,
        ),
    ]
