# Generated by Django 5.2.1 on 2025-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incomes", "0002_debtrepaymenthistorydealers"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtrepaymenthistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="debtrepaymenthistorydealers",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="income",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
