# Generated by Django 5.2.1 on 2025-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incomes", "0003_debtrepaymenthistory_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtrepaymenthistory",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debtrepaymenthistorydealers",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
