# Generated by Django 5.2.1 on 2025-07-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0006_dealergroup_updated_at"),
        ("incomes", "0004_debtrepaymenthistory_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="dealer_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.dealergroup",
            ),
        ),
    ]
