# Generated by Django 5.2.1 on 2025-05-28 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dealers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealergroup",
            name="members",
            field=models.ManyToManyField(
                related_name="dealer_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
