# Generated by Django 5.2.1 on 2025-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealergroup",
            name="debt",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
