# Generated by Django 5.2.1 on 2025-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0003_dealergroup_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealergroup",
            name="debt",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
