# Generated by Django 5.2.1 on 2025-05-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0004_alter_dealergroup_debt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealergroup",
            old_name="debt",
            new_name="total_debt",
        ),
    ]
