# Generated by Django 5.2.1 on 2025-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0005_rename_debt_dealergroup_total_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealergroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
