# Generated by Django 5.2.1 on 2025-05-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sold_sum_price",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                (
                    "stock_sum_price",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                (
                    "debt",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                ("paid", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutcomeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=10)),
                ("sold_price", models.DecimalField(decimal_places=5, max_digits=12)),
                ("stock_price", models.DecimalField(decimal_places=5, max_digits=12)),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_list",
                        to="sales.outcome",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
