# Generated by Django 5.2.1 on 2025-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcome",
            name="received_profit",
            field=models.BooleanField(default=False),
        ),
    ]
