# Generated by Django 5.2.1 on 2025-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_outcome_received_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outcome",
            name="debt",
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
