# Generated by Django 5.2.1 on 2025-07-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0006_dealergroup_updated_at"),
        ("sales", "0005_outcome_dealer_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outcome",
            name="dealer_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.dealergroup",
            ),
            preserve_default=False,
        ),
    ]
