# Generated by Django 5.2.1 on 2025-07-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0006_dealergroup_updated_at"),
        ("products", "0002_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dealer_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.dealergroup",
            ),
            preserve_default=False,
        ),
    ]
